# Generated by Django 4.1.5 on 2023-01-27 03:19

from django.db import migrations, models
import django.db.models.deletion
import utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bettable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(unique=True, verbose_name='value')),
            ],
            options={
                'verbose_name': 'Bettable',
                'ordering': ['value'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('start', utils.fields.FutureDateTimeField(verbose_name='start')),
                ('range', models.IntegerField(verbose_name='range')),
            ],
            options={
                'verbose_name': 'Tournament',
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='registered at')),
                ('choices', models.ManyToManyField(related_name='bet', related_query_name='bet', to='lottery.bettable', verbose_name='choices')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='lottery.tournament', verbose_name='Tournament')),
            ],
            options={
                'verbose_name': 'Bet',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='bet',
            constraint=models.UniqueConstraint(fields=('tournament', 'id'), name='bet_id'),
        ),
    ]
